on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: install github app
        id: gh-app
        uses: getsentry/action-github-app-token@v1.0.6
        with:
          app_id: ${{ secrets.ACS_APP_ID }}
          private_key: ${{ secrets.ACS_APP_PRIVATE_KEY }}

      - name: Invoke image introduction
        uses: actions/github-script@v6
        with:
          github-token: ${{ steps.gh-app.outputs.token }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'influxdata',
              repo: 'k8s-idpe',
              workflow_id: 'image-introduction.yml',
              ref: 'master',
              inputs: {
              mainBranch: "main",
              repo: "influxdb_iox",
              imageDirectoryPath: "iox",
              namespaceDir: "iox"
            },
            })
